dist: xenial
language: python
python:
  - '3.9'
install:
  - pip install -r requirements.txt
script:
  - python manage.py test --settings seven23.settings_tests
env:
  - SECRET_KEY="0nlyUsedforTesting0nlyUsedforTesting0nlyUsedforTes"