version: '3.1'

services:

  postgres:
    restart: always
    image: postgres:11-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=seven23
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=seven23

  seven23_server:
    build: .
    image: seven23_server:latest
    depends_on:
     - postgres
    ports:
     - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://seven23:password@postgres:5432/seven23
      - ALLOW_ACCOUNT_CREATION=True
      - DEBUG=True
      - EMAIL_PORT=${EMAIL_PORT-25}
      - SECRET_KEY=${SECRET_KEY-!!please-set-your-own-secret!!}
      - CONTACT_EMAIL=${CONTACT_EMAIL-admin@seven23.com}
      - EMAIL_HOST=${EMAIL_HOST-smtp.example.com}
